### ISSUE TITLE
App should targeted API level 30 as per google policies by November 2021.

### ISSUE THREAD

**Issue by Tan108** [Network-Revolution/DotLocalFinder#2]
As per google policies by November 2021, all the app updated must target Android 11(API level 30) but "DotLocalFinder" targeted SDK to 29.Please look into it and provide possible solution so that we will able to find Dot Local IP even after targeting to 30(if possible 31).

**Comment by NetworkRevolution** [comment]
the MulticastLock in SDK30/31 is dead. Everyone is downgrading to 29. There's no other way to fix the SDK.
https://github.com/Catfriend1/syncthing-android/issues/735
https://github.com/golang/go/issues/40569

Did you send an issue to the Android SDK? Or did you send a pull request?
https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-31
